# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train

  logdir: logs/dfaust/dfaust
  max_epoch: 600
  test_every_epoch: 10
  log_per_iter: 50
  ckpt_num: 200

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  step_size: (200,300)


DATA:
  train:
    name: pointcloud
    point_scale: 1.0
    point_sample_num: 10000

    # octree building
    depth: 8
    full_depth: 3

    # data loading
    location: data/dfaust/dataset
    filelist: data/dfaust/filelist/train.txt
    batch_size: 16
    # num_workers: 0

  test:
    name: pointcloud
    point_scale: 1.0
    point_sample_num: 10000

    # octree building
    depth: 8
    full_depth: 3

    # data loading
    location: data/dfaust/dataset
    filelist: data/dfaust/filelist/test.txt
    batch_size: 4
    # num_workers: 0


MODEL:
  name: graph_unet

  in_channels: 4
  resblk_type: basic
  feature: ND
  norm_type: batch_norm
  act_type: relu

  depth_out: 8

LOSS:
  name: dfaust
  loss_type: possion_grad_loss
