# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/dfaust_eval/dfaust
  ckpt: logs/dfaust/dfaust/checkpoints/00600.model.pth

  resolution: 300
  sdf_scale: 0.9
  save_sdf: False       # save the sdfs in evaluation


DATA:
  test:
    name: pointcloud
    point_scale: 1.0
    point_sample_num: 10000

    # octree building
    depth: 8
    full_depth: 3

    # data loading
    location: data/dfaust/dataset
    filelist: data/dfaust/filelist/test.txt
    batch_size: 1
    shuffle: False
    # num_workers: 0


MODEL:
  name: graph_unet

  in_channels: 4
  resblk_type: basic
  feature: ND
  norm_type: batch_norm
  act_type: relu
  group: 1

  depth_out: 8
