# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapenet_eval/ae
  ckpt: logs/shapenet/ae/checkpoints/00300.model.pth
  sdf_scale: 0.9
  resolution: 160


DATA:
  test:
    name: shapenet

    # octree building
    depth: 6
    offset: 0.0
    full_depth: 2
    node_dis: True
    split_label: True

    # no data augmentation
    distort: False

    # data loading
    location: data/ShapeNet/dataset
    filelist: data/ShapeNet/filelist/test_im.txt
    batch_size: 1
    shuffle: False
    load_sdf: False
    # num_workers: 0


MODEL:
  name: graph_ae

  channel: 4
  depth: 6
  nout: 4
  depth_out: 6
  full_depth: 2
  bottleneck: 4
  resblock_type: basic

LOSS:
  name: shapenet
  loss_type: sdf_reg_loss
