# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapes_eval
  ckpt: logs/dfaust/dfaust/checkpoints/00600.model.pth
  resolution: 420
  sdf_scale: 0.9


DATA:
  test:
    name: pointcloud
    point_scale: 0.9

    # octree building
    depth: 8
    full_depth: 3
    node_dis: True
    split_label: True
    offset: 0.0

    # data loading
    location: data/shapes
    filelist: data/shapes/filelist.txt
    batch_size: 1
    shuffle: False
    # num_workers: 0


MODEL:
  name: graph_unet

  in_channels: 4
  resblk_type: basic
  feature: ND
  norm_type: batch_norm
  act_type: relu

  depth_out: 8

