# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapenet_eval/ae
  ckpt: logs/shapenet/ae/checkpoints/00300.model.pth


  # sdf
  resolution: 160       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs

DATA:
  test:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # sdf
    load_occu: False  # load occupancy samples
    sample_surf_points: False
    load_sdf: False

    # data augmentation, add noise only
    distort: False

    # data loading
    location: data/ShapeNet/dataset
    filelist: data/ShapeNet/filelist/test_im.txt
    batch_size: 1
    shuffle: False
    # num_workers: 0


MODEL:
  name: graph_ae

  feature: ND
  channel: 4
  depth_out: 6

  bottleneck: 4
  resblock_type: basic

LOSS:
  name: shapenet
  loss_type: sdf_reg_loss
