# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapenet_eval/unseen5
  ckpt: logs/shapenet/shapenet/checkpoints/00300.model.pth

  # sdf
  resolution: 128       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs


DATA:
  test:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/ShapeNet/dataset.unseen5   # the original testing data
    filelist: data/ShapeNet/filelist/test_unseen5.txt
    batch_size: 1
    load_sdf: False
    shuffle: False
    in_memory: False
    # num_workers: 0


MODEL:
  name: graph_ounet

  channel: 5
  depth_out: 6

  bottleneck: 4
  resblock_type: basic