# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train

  logdir: logs/shapenet/ae
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 50
  ckpt_num: 40
  port: 10001

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  step_size: (160,240)

  # sdf
  resolution: 128       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs

DATA:
  train:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # sdf
    load_occu: False  # load occupancy samples
    point_sample_num: 10000
    sample_surf_points: False

    # data augmentation
    distort: False

    # data loading
    location: data/ShapeNet/dataset
    filelist: data/ShapeNet/filelist/train_im.txt
    load_sdf: True
    batch_size: 16
    shuffle: True
    # num_workers: 0

  test:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # sdf
    load_occu: False  # load occupancy samples
    point_sample_num: 10000
    sample_surf_points: False

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/ShapeNet/dataset
    filelist: data/ShapeNet/filelist/val_im.txt
    batch_size: 4
    load_sdf: True
    shuffle: False
    # num_workers: 0


MODEL:
  name: graph_ae

  in_channels: 4
  resblk_type: basic
  feature: ND
  norm_type: batch_norm
  act_type: relu

  depth_out: 6

LOSS:
  name: shapenet
  loss_type: sdf_reg_loss
