# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapenet_eval/test
  ckpt: logs/shapenet/shapenet/checkpoints/00300.model.pth

  # sdf
  resolution: 128       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs


DATA:
  test:
    name: pointcloud_eval

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # data loading
    # location: data/ShapeNet/dataset   # the original testing data
    location: data/ShapeNet/test.input  # the generated testing data
    filelist: data/ShapeNet/filelist/test.txt
    batch_size: 1
    shuffle: False
    in_memory: False
    # num_workers: 0


MODEL:
  name: graph_ounet

  in_channels: 3
  resblk_type: basic
  feature: L
  norm_type: batch_norm
  group: 1

  depth_out: 6
