# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapenet_eval/test
  ckpt: logs/shapenet/shapenet/checkpoints/00300.model.pth


DATA:
  test:
    name: pointcloud_eval

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # data loading
    # location: data/ShapeNet/dataset   # the original testing data
    location: data/ShapeNet/test.input  # the generated testing data
    filelist: data/ShapeNet/filelist/test.txt
    batch_size: 1
    shuffle: False
    in_memory: False

    # mesh extraction
    resolution: 128       # the resolution used for marching cubes
    save_sdf: False       # save the sdfs in evaluation
    sdf_scale: 0.9        # the scale of sdfs

MODEL:
  name: graph_ounet

  in_channels: 3
  resblk_type: basic
  feature: L
  norm_type: batch_norm
  act_type: relu

