# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapes_eval
  ckpt: logs/dfaust/dfaust/checkpoints/00600.model.pth


DATA:
  test:
    name: pointcloud
    point_scale: 0.9
    point_sample_num: 10000

    # octree building
    depth: 8
    full_depth: 3

    # data loading
    location: data/shapes
    filelist: data/shapes/filelist.txt
    batch_size: 1
    shuffle: False

    resolution: 420
    sdf_scale: 0.9
    save_sdf: False       # save the sdfs in evaluation

MODEL:
  name: graph_unet

  in_channels: 4
  resblk_type: basic
  feature: ND
  norm_type: batch_norm
  act_type: relu
