# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train

  logdir: logs/shapenet/shapenet
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 50
  ckpt_num: 40

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  step_size: (160,240)

  # sdf
  resolution: 128       # the resolution used for marching cubes
  save_sdf: False       # save the sdfs in evaluation
  sdf_scale: 0.9        # the scale of sdfs

DATA:
  train:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # sdf
    load_occu: False  # load occupancy samples
    point_sample_num: 10000
    sample_surf_points: False

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/ShapeNet/dataset
    filelist: data/ShapeNet/filelist/train.txt
    load_sdf: True
    batch_size: 16
    shuffle: True
    # num_workers: 0

  test:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # sdf
    load_occu: False  # load occupancy samples
    point_sample_num: 10000
    sample_surf_points: False

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/ShapeNet/dataset
    filelist: data/ShapeNet/filelist/val.txt
    batch_size: 8
    load_sdf: True
    shuffle: False
    # num_workers: 0


MODEL:
  name: graph_ounet

  feature: L
  channel: 3
  depth_out: 6

  bottleneck: 4
  resblock_type: basic

LOSS:
  name: shapenet
  loss_type: sdf_reg_loss
