# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/shapenet_eval/unseen5
  ckpt: logs/shapenet/shapenet/checkpoints/00300.model.pth


DATA:
  test:
    name: shapenet

    # octree building
    depth: 6
    full_depth: 3
    point_scale: 0.5  # the scale of point clouds

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/ShapeNet/dataset.unseen5   # the original testing data
    filelist: data/ShapeNet/filelist/test_unseen5.txt
    batch_size: 1
    load_sdf: False
    load_occu: False
    sample_surf_points: False
    shuffle: False
    in_memory: False

    # sdf
    resolution: 128       # the resolution used for marching cubes
    save_sdf: False       # save the sdfs in evaluation
    sdf_scale: 0.9        # the scale of sdfs

MODEL:
  name: graph_ounet

  in_channels: 3
  resblk_type: basic
  feature: L
  norm_type: batch_norm
  act_type: relu
