# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/room_eval/room
  ckpt: logs/room/room/checkpoints/00900.model.pth


DATA:
  test:
    name: pointcloud_eval

    # octree building
    depth: 7
    full_depth: 3
    point_scale: 0.6

    # data augmentation
    distort: False

    # data loading
    # location: data/room/synthetic_room_dataset
    location: data/room/test.input  # the generated testing data
    filelist: data/room/filelist/test.txt
    batch_size: 1
    shuffle: False
    in_memory: False
    # num_workers: 0

    # sdf
    sdf_scale: 0.9
    resolution: 280
    save_sdf: False       # save the sdfs in evaluation

MODEL:
  name: graph_ounetr

  in_channels: 3
  resblk_type: basic
  feature: L
  norm_type: batch_norm
  act_type: relu
