# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  logdir: logs/room_eval/room
  ckpt: logs/room/room/checkpoints/00900.model.pth
  sdf_scale: 0.9
  resolution: 280

DATA:
  test:
    name: pointcloud_eval
    point_scale: 0.6

    # octree building
    depth: 7
    offset: 0.0
    full_depth: 3
    node_dis: True
    split_label: True

    # data augmentation, add noise only
    # distort: True

    # data loading
    # location: data/room/synthetic_room_dataset
    location: data/room/test.input  # the generated testing data
    filelist: data/room/filelist/test.txt
    batch_size: 1
    shuffle: False
    in_memory: False
    # num_workers: 0


MODEL:
  name: graph_ounet

  channel: 5
  depth: 7
  nout: 4
  depth_out: 7
  full_depth: 3
  bottleneck: 4
  resblock_type: basic
