# --------------------------------------------------------
# Dual Octree Graph Neural Networks
# Copyright (c) 2024 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train

  logdir: logs/room/room
  max_epoch: 900
  test_every_epoch: 10
  log_per_iter: 40
  ckpt_num: 20

  type: adamw
  lr: 0.00025
  weight_decay: 0.01  # default value of adamw
  lr_type: poly
  step_size: (80,120)


DATA:
  train:
    name: synthetic_room

    # octree building
    depth: 7
    full_depth: 3

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/room/synthetic_room_dataset
    filelist: data/room/filelist/train.txt
    load_occu: True
    sample_surf_points: True
    batch_size: 4
    shuffle: True
    # num_workers: 0

  test:
    name: synthetic_room

    # octree building
    depth: 7
    full_depth: 3

    # data augmentation, add noise only
    distort: True

    # data loading
    location: data/room/synthetic_room_dataset
    filelist: data/room/filelist/val.txt
    load_occu: True
    sample_surf_points: True
    batch_size: 2
    shuffle: False
    # num_workers: 0


MODEL:
  name: graph_ounetr

  in_channels: 3
  resblk_type: basic
  feature: L
  norm_type: batch_norm
  act_type: relu


LOSS:
  name: synthetic_room
